FROM node:14-alpine as build

WORKDIR /frontend

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

FROM node:14.9.0-alpine

WORKDIR /frontend

COPY --from=build /frontend/node_modules ./node_modules
COPY --from=build /frontend/.next ./.next

EXPOSE 3000

CMD ["npm", "start"]
