# Generated by Django 3.2 on 2022-07-29 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_artist_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playhistory',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to='app.track'),
        ),
    ]
