# Generated by Django 3.2 on 2022-12-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20221003_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='artist',
            name='tracks',
        ),
        migrations.AddField(
            model_name='artist',
            name='tracks',
            field=models.ManyToManyField(blank=True, null=True, related_name='artist_tracks', to='app.Track'),
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='artists', to='app.Genre'),
        ),
    ]
