# Generated by Django 3.2 on 2022-10-03 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_playhistory_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playhistory',
            old_name='created_at',
            new_name='added_at',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='duration',
            new_name='duration_ms',
        ),
    ]
