# Generated by Django 3.2 on 2023-04-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_data',
            field=models.JSONField(default=dict),
        ),
    ]
