# Generated by Django 3.2 on 2022-08-06 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spotify_app', '0006_add_user_relation_to_play_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='playhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_play_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
