name: Build and Lint
on:
 push:
  branches:
   - '*'

jobs:
 docker:
  timeout-minutes: 10
  runs-on: ubuntu-latest

  steps:
   - name: Checkout
     uses: actions/checkout@v2
   
   - name: Use Node.js 16.20.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.0

      - name: Install npm 8.19.4
        run: npm install -g npm@8.19.4

   - name: Start Containers
     run: docker-compose -f "docker-compose.prod.yml" up -d --env_file ./.env.sample
   - name: Frontend Packages
     run: cd frontend && npm install
   - name: Frontend Linting
     run: cd frontend && npm run lint
